### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by Tsiems** [CompFit/CompFit#15]
It must be beautiful

**Comment by EmVilleda** [comment]
Created several logo versions and ran them through the team to decide. After discussing each we've decided on the first flag version (see attached). Will update with colors soon.

All Versions:
![logo-versions](https://cloud.githubusercontent.com/assets/6711649/14186415/e5ef7ef2-f743-11e5-99d8-7e3d8c5e2641.png)

Selected:
![logo](https://cloud.githubusercontent.com/assets/6711649/14186431/f4d4bb44-f743-11e5-80d3-4e8d18dfb6e4.png)
