### ISSUE TITLE
Show team progress on Challenge page with progress bar

### ISSUE THREAD

**Issue by Tsiems** [CompFit/CompFit#186]
Needs to be big, clear, and probably in the top section of each panel

**Comment by EmVilleda** [comment]
Been added by Travis. Might need to adjust colors though.

![screen shot 2016-04-26 at 11 46 48 am](https://cloud.githubusercontent.com/assets/6711649/14826696/ab7f0074-0ba4-11e6-8e75-878aed579742.png)
