### ISSUE TITLE
Make All Endpoints in Slim PHP (only skeleton form) 

### ISSUE THREAD

**Issue by Tsiems** [CompFit/CompFit#39]
refer to Apiary for which functions (GET/POST/PUT/DELETE) you need for each
- [x] User
- [x] Users
- [x] Team
- [x] Teams
- [x] Challenge
- [x] Challenges
- [x] Exercise
- [x] Exercises

**Comment by eesharp** [comment]
I wrote the skeleton for all the end points, but I wasn't sure what the auth end point was supposed to consist of as it wasn't on apiary.

**Comment by Tsiems** [comment]
Auth endpoint was meant for login. Since you have came up with a new way to do the Apiary/API in a RESTful way, you and the rest of the DB team can let us know what endpoint we should use.
