### ISSUE TITLE
Make Apiary calls consistent

### ISSUE THREAD

**Issue by Tsiems** [CompFit/CompFit#53]
Some of the Apiary response calls could be formatted better to have fewer parts to worry about.
Also, make sure that everything is in proper JSON format.

Examples:
Users returns

```
[
    { 
        "users": [ {...},{...} ]
    }  
]
```

which could be formatted to be just
`[ {...},{...} ]`

Fixed endpoints:
- [x] Users
- [x] Teams
- [x] Check the rest of them

**Comment by jsaurino** [comment]
Feel free to check my edits and make sure they are up to standard
