### ISSUE TITLE
Include challenges table

### ISSUE THREAD

**Issue by Tsiems** [CompFit/CompFit#6]
- [x] Challenge_id (primary, auto-inc)
- [x] Start_date
- [x] End_date
- [x] From_team_id
- [x] to_team_id
- [x] Task_name
- [x] Repetitions
- [x] Units
- [x] Task_type
- [x] Status (accept/reject/pending)
- [x] Created (timestamp)

**Comment by eesharp** [comment]
Done. compFitDatabase.sql
